services:
  leaderboard:
    container_name: leaderboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3781:8001"
    environment:
      - REDIS_ADDR=leaderboard-redis:6379
      - KAFKA_ADDR=kafka:9092
    restart: unless-stopped
    depends_on:
      - leaderboard-redis
    networks:
      - app-net

  leaderboard-redis:
    container_name: leaderboard-redis
    image: redis:7-alpine
    ports:
      - "6381:6379"
    restart: always
    command: redis-server --appendonly yes --appendfsync everysec --auto-aof-rewrite-percentage 100 --auto-aof-rewrite-min-size 64mb
    volumes:
      - leaderboard-redis-data:/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  leaderboard-redis-data:
