include:
  - ./bot/docker-compose.prod.yml
  - ./account/docker-compose.prod.yml
  - ./shop/docker-compose.prod.yml
  - ./battle/docker-compose.prod.yml
  - ./leaderboard/docker-compose.prod.yml

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /home/node/app
    volumes:
      - frontend-dist:/home/node/app/dist
    command: ["npm", "run", "build"]
    stop_signal: SIGINT
    depends_on:
      - account
    networks:
      - app-net

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend-dist:/src/public:ro
    depends_on:
      - account
      - frontend
      - battle
      - shop
      - leaderboard
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.4.10
    container_name: kafka
    expose:
      - "9092"
      - "29093"
    environment:
      CLUSTER_ID: "MkU3o6n8QrO2VZk5eY1hnA"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT://:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: kafka-ui
    expose:
      - "8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - app-net

networks:
  app-net:

volumes:
  frontend-dist:
  kafka-data:
