include:
  - ./bot/docker-compose.yml
  - ./account/docker-compose.yml
  - ./shop/docker-compose.yml
  - ./battle/docker-compose.yml

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /home/node/app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "dev", "--host"]
    stop_signal: SIGINT
    depends_on:
      - account
    networks:
      - app-net

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/app/miniapp:/src/public
    depends_on:
      - account
      - frontend
      - battle
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.4.10
    container_name: kafka
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:
      CLUSTER_ID: "MkU3o6n8QrO2VZk5eY1hnA"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT://:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - app-net

networks:
  app-net:
