// Code generated by tools/generate_combat_profile.py; DO NOT EDIT.
package game

const (
	CombatProfileID            = "combat-profile"
	CombatProfileSchemaVersion = 1
	CombatProfileRevision      = "2026-08-26-phase-1-combat-core"
	CombatRulesVersion         = "2026-08-26-phase-1-combat-core"
	CombatProfileFingerprint   = "3B2F8D0486E03BA44B3A706E5E547BCA7AA1E3AEADDAA88462C56C41D9233BD4"
)

const GeneratedCombatProfileJSON = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "schemaVersion": 1,
  "profileId": "combat-profile",
  "profileRevision": "2026-08-26-phase-1-combat-core",
  "purpose": "Версионируемый контракт authoritative combat core и его runtime-представлений.",
  "modes": [
    "deathmatch",
    "team deathmatch"
  ],
  "defaults": {
    "super": {
      "maxChargePercent": 100,
      "startChargePercent": 0,
      "chargeSources": [
        "effective_damage",
        "control",
        "support",
        "objective"
      ]
    },
    "gadget": {
      "maxCharges": 3,
      "chargesOnSpawn": 3,
      "cooldownPolicy": "profile"
    },
    "healthBoost": {
      "pickupId": "health_boost",
      "stat": "maxLives",
      "fraction": 0.05,
      "maxStacks": 5,
      "ttlMs": 30000,
      "healsCurrentLives": false
    },
    "respawn": {
      "preserveHealthBoostStacks": true,
      "resetSuperCharge": true,
      "resetStatuses": true,
      "refillAmmo": true,
      "preserveGadgetCharges": true
    },
    "pickup": {
      "claimPolicy": "one_time_team_claim",
      "collectorOnly": true
    },
    "loot": {
      "healthPickupIds": [
        "health_boost"
      ],
      "nonHpPickupIds": [
        "lunar_speed",
        "lunar_damage",
        "lunar_shield",
        "lunar_cooldown"
      ],
      "nonHpPickupMode": "optional_bonus",
      "nonHpAffectsCurrentLives": false
    },
    "bats": {
      "role": "contested_resource",
      "respawnPolicy": "deterministic_camp_once",
      "target": "combat_impact"
    },
    "telegraph": {
      "minDurationMs": 250
    },
    "ai": {
      "lowHealthRetreatFraction": 0.3,
      "criticalHealthRetreatFraction": 0.15,
      "superUseAdvantageFraction": 0.2,
      "pickupContestHealthFraction": 0.65
    }
  },
  "heroes": {
    "needle": {
      "role": "Controller",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.55,
        "control": 0.95,
        "safety": 0.55,
        "mobility": 0.75,
        "sustain": 0.35,
        "information": 0.85,
        "objectiveValue": 0.65
      },
      "basic": {
        "abilityId": "spore_thorn",
        "attackType": "spore",
        "attackDamage": 60,
        "attackCooldownMs": 420,
        "reloadTimeMs": 1750,
        "maxAmmo": 3,
        "archetype": "projectile",
        "range": 620
      },
      "super": {
        "abilityId": "hunter_root",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "spore_escape",
        "maxCharges": 3
      }
    },
    "mandy": {
      "role": "Fighter",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.85,
        "control": 0.7,
        "safety": 0.65,
        "mobility": 0.5,
        "sustain": 0.55,
        "information": 0.25,
        "objectiveValue": 0.7
      },
      "basic": {
        "abilityId": "staff_strike",
        "attackType": "mandy_staff",
        "attackDamage": 100,
        "attackCooldownMs": 420,
        "reloadTimeMs": 1650,
        "maxAmmo": 3,
        "archetype": "melee_cone",
        "range": 110
      },
      "super": {
        "abilityId": "devastation_wave",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "unyielding_stance",
        "maxCharges": 3
      }
    },
    "fairy-mina": {
      "role": "Support",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.55,
        "control": 0.55,
        "safety": 0.75,
        "mobility": 0.5,
        "sustain": 0.95,
        "information": 0.45,
        "objectiveValue": 0.5
      },
      "basic": {
        "abilityId": "star_fan",
        "attackType": "mina_star_fan",
        "attackDamage": 55,
        "attackCooldownMs": 420,
        "reloadTimeMs": 1550,
        "maxAmmo": 3,
        "archetype": "shotgun",
        "range": 510
      },
      "super": {
        "abilityId": "star_cocoon",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "repelling_wave",
        "maxCharges": 3
      }
    },
    "brock-zeus": {
      "role": "Sharpshooter",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.95,
        "control": 0.4,
        "safety": 0.3,
        "mobility": 0.35,
        "sustain": 0.25,
        "information": 0.65,
        "objectiveValue": 0.55
      },
      "basic": {
        "abilityId": "thunder_projectile",
        "attackType": "zeus_lightning",
        "attackDamage": 85,
        "attackCooldownMs": 520,
        "reloadTimeMs": 1800,
        "maxAmmo": 3,
        "archetype": "projectile",
        "range": 760
      },
      "super": {
        "abilityId": "gods_hammer",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "discharge_cable",
        "maxCharges": 3
      }
    },
    "kaze": {
      "role": "Assassin",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.9,
        "control": 0.55,
        "safety": 0.35,
        "mobility": 0.95,
        "sustain": 0.25,
        "information": 0.5,
        "objectiveValue": 0.35
      },
      "basic": {
        "abilityId": "cross_slash",
        "attackType": "kaze_cross_slash",
        "attackDamage": 85,
        "attackCooldownMs": 280,
        "reloadTimeMs": 1050,
        "maxAmmo": 3,
        "archetype": "melee_cone",
        "range": 125
      },
      "super": {
        "abilityId": "piercing_dash",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "vanish",
        "maxCharges": 3
      }
    },
    "wukong-mico": {
      "role": "Tank",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.7,
        "control": 0.6,
        "safety": 0.95,
        "mobility": 0.45,
        "sustain": 0.75,
        "information": 0.25,
        "objectiveValue": 0.6
      },
      "basic": {
        "abilityId": "heavy_staff",
        "attackType": "mico_staff",
        "attackDamage": 100,
        "attackCooldownMs": 650,
        "reloadTimeMs": 1750,
        "maxAmmo": 3,
        "archetype": "melee_cone",
        "range": 140
      },
      "super": {
        "abilityId": "vengeance_vortex",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "stone_armor",
        "maxCharges": 3
      }
    },
    "persephone-lumi": {
      "role": "Controller",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.65,
        "control": 0.9,
        "safety": 0.45,
        "mobility": 0.45,
        "sustain": 0.6,
        "information": 0.75,
        "objectiveValue": 0.65
      },
      "basic": {
        "abilityId": "luminous_flower",
        "attackType": "lumi_orb",
        "attackDamage": 60,
        "attackCooldownMs": 470,
        "reloadTimeMs": 1600,
        "maxAmmo": 3,
        "archetype": "projectile",
        "range": 520
      },
      "super": {
        "abilityId": "root_garden",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "flower_burst",
        "maxCharges": 3
      }
    },
    "katty": {
      "role": "Controller",
      "powerBudget": 1.0,
      "powerBudgetVector": {
        "threat": 0.6,
        "control": 0.9,
        "safety": 0.6,
        "mobility": 0.8,
        "sustain": 0.3,
        "information": 0.65,
        "objectiveValue": 0.75
      },
      "basic": {
        "abilityId": "paint_spray",
        "attackType": "katty_paint_spray",
        "attackDamage": 55,
        "attackCooldownMs": 520,
        "reloadTimeMs": 1700,
        "maxAmmo": 3,
        "archetype": "projectile",
        "range": 220
      },
      "super": {
        "abilityId": "paint_grenade",
        "chargeWeight": 1.0
      },
      "gadget": {
        "abilityId": "paint_flight",
        "maxCharges": 3
      }
    }
  }
}
`
