services:
  shop:
    container_name: shop
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file: ../.env
    environment:
      SHOP_DB_HOST: shop-db
      REDIS_HOST: redis
      REDIS_PORT: 6388
      KAFKA_ADDR: kafka:9092
      APP_ENV: development
      APP_AUTH_SECRET: "${APP_AUTH_SECRET:-local-development-auth-secret-change-before-production}"
    restart: unless-stopped
    depends_on:
      - shop-db
    networks:
      - app-net

  shop-db:
    container_name: shop-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    command: "postgres -c max_connections=150 -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2 -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    environment:
      POSTGRES_USER: someusername
      POSTGRES_PASSWORD: postgres_pass12345
      POSTGRES_DB: bot
    networks:
      - app-net

networks:
  app-net:

volumes:
  shop-db-data:
