"""initial

Revision ID: 6ce24c65a3d4
Revises: 
Create Date: 2024-12-23 18:22:56.452424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ce24c65a3d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('clicks', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('completed_tasks', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('tb_username', sa.String(length=128), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('invites',
    sa.Column('invite_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.BIGINT(), nullable=False),
    sa.Column('invitee_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invite_id'),
    sa.UniqueConstraint('invitee_id'),
    sa.UniqueConstraint('inviter_id', 'invitee_id', name='unique_invites')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    op.drop_table('users')
    # ### end Alembic commands ###
