services:
  account:
    container_name: account
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file: ../.env
    environment:
      DB_HOST: db
      KAFKA_ADDR: kafka:9092
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
