services:
  account:
    container_name: account
    image: account
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file: ../.env
    environment:
      DB_HOST: db
      KAFKA_ADDR: kafka:9092
      APP_ENV: "production"
    restart: always
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  app-net:
