services:
  account:
    container_name: account
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file: ../.env
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
