[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "account"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy~=2.0",
    "asyncpg",
    "environs~=14.2.0",
    "uvicorn[standard]~=0.34",
    "fastapi~=0.115",
    "httpx~=0.28.1",
    "aiokafka~=0.12",
]

[tool.setuptools]
py-modules = ["app", "config", "db", "deps", "routes", "schemas"]

[tool.setuptools.packages.find]
include = ["infrastructure*", "routes*", "schemas*", "services*"]
