root = "."
tmp_dir = "."

[build]
cmd = "go build -o ./battle.exe ."
bin = "./battle.exe"
include_ext = ["go"]
exclude_dir = ["tmp", ".git"]
delay = 1000
poll = true
poll_interval = 1000
stop_on_error = false
send_interrupt = true
kill_delay = "2s"

[log]
time = true

[misc]
clean_on_exit = false
