package handler

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const mapEditorBodyLimit = 8 << 20

type mapEditorApplyRequest struct {
	Map      string             `json:"map"`
	Walls    []mapEditorWall    `json:"walls"`
	Features []mapEditorFeature `json:"features"`
}

type mapEditorWall struct {
	MinX            float64 `json:"minX"`
	MinY            float64 `json:"minY"`
	MaxX            float64 `json:"maxX"`
	MaxY            float64 `json:"maxY"`
	Type            string  `json:"type"`
	Rotation        float64 `json:"rotation"`
	LinkedFeatureID string  `json:"linkedFeatureId"`
	BushGroup       int     `json:"bushGroup"`
	ColliderInsetX  float64 `json:"colliderInsetX"`
	ColliderInsetY  float64 `json:"colliderInsetY"`
	ColliderRadius  float64 `json:"colliderRadius"`
}

type mapEditorFeature struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Rotation float64 `json:"rotation"`
	Scale    float64 `json:"scale"`
}

func (h *Handler) HandleMapEditorApply(w http.ResponseWriter, r *http.Request) {
	if strings.EqualFold(strings.TrimSpace(os.Getenv("APP_ENV")), "production") {
		http.NotFound(w, r)
		return
	}
	if r.Method != http.MethodPost {
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}

	var request mapEditorApplyRequest
	decoder := json.NewDecoder(io.LimitReader(r.Body, mapEditorBodyLimit))
	if err := decoder.Decode(&request); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid map editor payload"})
		return
	}
	if request.Map != "team-battle-northern" && request.Map != "team-battle" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "unsupported team battle map"})
		return
	}
	if err := validateMapEditorPayload(request); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}

	target := mapEditorSourceFile(request.Map)
	if err := writeMapEditorSource(target, renderMapEditorSource(request)); err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "could not write map source"})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "map": request.Map, "path": target})
}

func validateMapEditorPayload(request mapEditorApplyRequest) error {
	if len(request.Walls) > 20000 || len(request.Features) > 2000 {
		return fmt.Errorf("map editor payload is too large")
	}
	for _, wall := range request.Walls {
		if wall.Type == "" || !finiteMapEditorNumbers(wall.MinX, wall.MinY, wall.MaxX, wall.MaxY, wall.Rotation, wall.ColliderInsetX, wall.ColliderInsetY, wall.ColliderRadius) {
			return fmt.Errorf("map editor contains an invalid wall")
		}
		if wall.MinX > wall.MaxX || wall.MinY > wall.MaxY {
			return fmt.Errorf("map editor contains an inverted wall")
		}
	}
	for _, feature := range request.Features {
		if feature.ID == "" || feature.Type == "" || !finiteMapEditorNumbers(feature.X, feature.Y, feature.Rotation, feature.Scale) {
			return fmt.Errorf("map editor contains an invalid feature")
		}
	}
	return nil
}

func finiteMapEditorNumbers(values ...float64) bool {
	for _, value := range values {
		if math.IsNaN(value) || math.IsInf(value, 0) {
			return false
		}
	}
	return true
}

func mapEditorSourceFile(mapName string) string {
	if configured := strings.TrimSpace(os.Getenv("MAP_EDITOR_SOURCE_FILE")); configured != "" {
		return configured
	}
	if mapName == "team-battle" {
		return filepath.FromSlash("model/gamemap/edited_team_battle_classic_map.go")
	}
	return filepath.FromSlash("model/gamemap/edited_team_battle_northern_map.go")
}

func writeMapEditorSource(target string, source []byte) (err error) {
	directory := filepath.Dir(target)
	temporary, err := os.CreateTemp(directory, ".map-editor-*.go")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer func() {
		_ = temporary.Close()
		if err != nil {
			_ = os.Remove(temporaryName)
		}
	}()
	if _, err = temporary.Write(source); err != nil {
		return err
	}
	if err = temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, target)
}

func renderMapEditorSource(request mapEditorApplyRequest) []byte {
	functionName := "applyEditedTeamBattleNorthernMap"
	if request.Map == "team-battle" {
		functionName = "applyEditedTeamBattleClassicMap"
	}
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by map-environment-harness.\n// This file is written by the local development map editor.\npackage gamemap\n\nimport \"battle/service/geometry\"\n\nfunc %s(gm *GameMap) {\n\tgm.Collisions = []*geometry.WallTile{\n", functionName)
	for _, wall := range request.Walls {
		fields := []string{
			fmt.Sprintf("MinX: %s", mapEditorFloat(wall.MinX)),
			fmt.Sprintf("MinY: %s", mapEditorFloat(wall.MinY)),
			fmt.Sprintf("MaxX: %s", mapEditorFloat(wall.MaxX)),
			fmt.Sprintf("MaxY: %s", mapEditorFloat(wall.MaxY)),
			fmt.Sprintf("Type: %s", strconv.Quote(wall.Type)),
		}
		if wall.Rotation != 0 {
			fields = append(fields, fmt.Sprintf("Rotation: %s", mapEditorFloat(wall.Rotation)))
		}
		if wall.BushGroup != 0 {
			fields = append(fields, fmt.Sprintf("BushGroup: %d", wall.BushGroup))
		}
		if wall.ColliderInsetX != 0 {
			fields = append(fields, fmt.Sprintf("ColliderInsetX: %s", mapEditorFloat(wall.ColliderInsetX)))
		}
		if wall.ColliderInsetY != 0 {
			fields = append(fields, fmt.Sprintf("ColliderInsetY: %s", mapEditorFloat(wall.ColliderInsetY)))
		}
		if wall.ColliderRadius != 0 {
			fields = append(fields, fmt.Sprintf("ColliderRadius: %s", mapEditorFloat(wall.ColliderRadius)))
		}
		if wall.LinkedFeatureID != "" {
			fields = append(fields, fmt.Sprintf("LinkedFeatureID: %s", strconv.Quote(wall.LinkedFeatureID)))
		}
		fmt.Fprintf(&source, "\t\t{%s},\n", strings.Join(fields, ", "))
	}
	source.WriteString("\t}\n\tgm.Features = []MapFeature{\n")
	for _, feature := range request.Features {
		scale := feature.Scale
		if scale <= 0 {
			scale = 1
		}
		fmt.Fprintf(&source, "\t\t{ID: %s, Type: %s, X: %s, Y: %s, Rotation: %s, Scale: %s},\n",
			strconv.Quote(feature.ID), strconv.Quote(feature.Type), mapEditorFloat(feature.X), mapEditorFloat(feature.Y), mapEditorFloat(feature.Rotation), mapEditorFloat(scale))
	}
	source.WriteString("\t}\n}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return []byte(source.String())
	}
	return formatted
}

func mapEditorFloat(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}
