"""Generate deterministic combat-profile views for backend and frontend."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any

from validate_combat_profile import (
    ROOT,
    read_catalog,
    read_profile,
    validate_profile,
)


GO_OUTPUT = ROOT / "battle" / "model" / "game" / "combat_profile_generated.go"
FRONTEND_OUTPUT = (
    ROOT / "frontend" / "src" / "components" / "BattleGame" / "combatProfile.generated.js"
)
FINGERPRINT_OUTPUT = ROOT / "docs" / "combat-profile.fingerprint.json"


def canonical_profile_bytes(profile: dict[str, Any]) -> bytes:
    return json.dumps(
        profile, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def profile_fingerprint(profile: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_profile_bytes(profile)).hexdigest().upper()


def render_profile_json(profile: dict[str, Any]) -> str:
    return json.dumps(profile, ensure_ascii=False, indent=2) + "\n"


def render_go(profile: dict[str, Any], fingerprint: str) -> str:
    profile_json = render_profile_json(profile)
    source = (
        "// Code generated by tools/generate_combat_profile.py; DO NOT EDIT.\n"
        "package game\n\n"
        "const (\n"
        f'\tCombatProfileID = "{profile["profileId"]}"\n'
        f"\tCombatProfileSchemaVersion = {profile['schemaVersion']}\n"
        f'\tCombatProfileRevision = "{profile["profileRevision"]}"\n'
        f'\tCombatRulesVersion = "{profile["profileRevision"]}"\n'
        f'\tCombatProfileFingerprint = "{fingerprint}"\n'
        ")\n\n"
        "const GeneratedCombatProfileJSON = `"
        + profile_json
        + "`\n"
    )
    result = subprocess.run(
        ["gofmt"],
        input=source,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=True,
    )
    return result.stdout


def render_frontend(profile: dict[str, Any], fingerprint: str) -> str:
    profile_json = render_profile_json(profile).rstrip("\n")
    return (
        "// Code generated by tools/generate_combat_profile.py; DO NOT EDIT.\n"
        f"export const COMBAT_PROFILE_ID = {json.dumps(profile['profileId'])}\n"
        f"export const COMBAT_PROFILE_SCHEMA_VERSION = {profile['schemaVersion']}\n"
        f"export const COMBAT_PROFILE_REVISION = {json.dumps(profile['profileRevision'])}\n"
        f"export const COMBAT_RULES_VERSION = {json.dumps(profile['profileRevision'])}\n"
        f"export const COMBAT_PROFILE_FINGERPRINT = {json.dumps(fingerprint)}\n"
        f"export const COMBAT_PROFILE = {profile_json}\n"
    )


def render_fingerprint_report(profile: dict[str, Any], fingerprint: str) -> str:
    report = {
        "profileId": profile["profileId"],
        "schemaVersion": profile["schemaVersion"],
        "profileRevision": profile["profileRevision"],
        "fingerprint": fingerprint,
        "generatedViews": [
            "battle/model/game/combat_profile_generated.go",
            "frontend/src/components/BattleGame/combatProfile.generated.js",
        ],
    }
    return json.dumps(report, ensure_ascii=False, indent=2) + "\n"


def expected_artifacts() -> dict[Path, str]:
    profile = read_profile()
    errors = validate_profile(profile, read_catalog())
    if errors:
        raise ValueError("invalid combat profile: " + "; ".join(errors))
    fingerprint = profile_fingerprint(profile)
    return {
        GO_OUTPUT: render_go(profile, fingerprint),
        FRONTEND_OUTPUT: render_frontend(profile, fingerprint),
        FINGERPRINT_OUTPUT: render_fingerprint_report(profile, fingerprint),
    }


def validate_generated_artifacts() -> list[str]:
    try:
        expected = expected_artifacts()
    except (OSError, json.JSONDecodeError, TypeError, ValueError) as exc:
        return [str(exc)]
    errors: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            errors.append(f"generated artifact is missing: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"generated artifact is stale: {path.relative_to(ROOT)}")
    return errors


def generate() -> None:
    for path, content in expected_artifacts().items():
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    if args.check:
        errors = validate_generated_artifacts()
        if errors:
            for error in errors:
                print(f"[ERROR] {error}")
            return 1
        print("[OK] generated combat profile views are up to date")
        return 0
    generate()
    print(f"[OK] generated {GO_OUTPUT.relative_to(ROOT)} and {FRONTEND_OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
